### PR TITLE
add android-10, android-15 update android_acm_serial

### PR DESCRIPTION
**Pull request by talregev**
compile the latest android core for indigo, and upload android_10, android_15, and  android_acm_serial.
please approve.

### CODE REVIEW

**Comment by talregev** [comment]
@damonkohler @SirVer  can you look at this?

**Comment by SirVer** [comment]
I do not feel qualified to comment on this change, I have not much experience with maven.

**Comment by talregev** [comment]
i have also update opencv, dnsjava, junit library. 
I consider to add opencv from 2.4.9-4 till 2.4.9-7 but it cost 207 MB.
from here:
http://central.maven.org/maven2/nu/pattern/opencv/

it is worth? 
If you approve, i will added to my repository and send you a pull request.
Thanks, Tal.

**Comment by stonier** [comment]
@talregev is that opencv something that you can't pick up from `mavenCentral()`?

**Comment by stonier** [comment]
Lots of additions here - I'm setting up an indigo workspace now and will check that everything still works with all of these additions.

**Comment by talregev** [comment]
there is no opencv in mavenCentral().
there in other mavens, but i compile it myself and add it to here.

i am not sure about rosjava_messages v0.1.321 and ect. i want to delete it from repository.
i am think it a bug when you previous compile a messages and then you delete the source,
it still generate rosjava_messages but in it own package version (v0.1.321 and ect ...)
can you verify it for me?

**Comment by stonier** [comment]
> there is no opencv in mavenCentral(). there in other mavens, but i compile it myself and add it to here.

Using opencv from elsehwere...is it easy enough to add a maven url link to it from a `build.gradle` file that requires it? i.e.

```
maven {
      url "http://we.can.find/opencv/here"
    }
```

Github is a very simple way of collaborating on a maven repository, and one that most ros people are familiar with. But its not ideal as it's not strictly a file server - can't let it become gigabytes big, so I'd prefer this just kept  ros packages and a few esoteric dependencies.

Having said that, opencv is a nice one to make available, or have instructions on how to access it. Perhaps if you can simply get access it to as above, then let's start keeping a list of useful maven URL's in the README to this repo.

**Comment by stonier** [comment]
> i am not sure about rosjava_messages v0.1.321 and ect. i want to delete it from repository.
> i am think it a bug when you previous compile a messages and then you delete the source,
> it still generate rosjava_messages but in it own package version (v0.1.321 and ect ...)
> can you verify it for me?

Not sure what you are driving at here...care to elaborate?

**Comment by talregev** [comment]
i have a list of maven repository for all the jar that you have added.
maybe will add a build.gradle with all necessary maven repository instead to keep them all here. 

can you look at this list?
https://github.com/talregev/rosjava_mvn_repo/blob/master/list_of_repositories_to_update

in the evening i will constract that file and added to here,
but meybe need to change some of the ros project if we do it,
because it not save as at our maven repository.

what do you think?

**Comment by stonier** [comment]
Oh, that's nice. I originally got most of required rosjava dependencies in this repo from another one that Damon & others had put together. While I usually prefer to do things 'upstream', I think it's worthwhile having the collection of all the dependencies rosjava needs in one place rather than having to keep an eye on the validity of other repositories. We don't have the manpower or number of users for that.

Added this information to the [README](https://github.com/rosjava/rosjava_mvn_repo/blob/master/README.md)

**Comment by stonier** [comment]
Question:

Why isn't this link, http://central.maven.org/maven2/nu/pattern/opencv/, automatically found via the `mavenCentral()` alias?

**Comment by stonier** [comment]
Rosjava indigo stacks are compiling ok with this pull request..haven't tried the android stacks yet.

**Comment by talregev** [comment]
which project from rosjave pull from this repository?
some of the jar version can be update like javadns 2.1.6 instead of 2.1.1
and there a new project of netty. like netty-all 

maybe the interface in this jar didn't change and can be added easily to rosjava project.

**Comment by talregev** [comment]
i think that need to arrange this repository before make it official

**Comment by talregev** [comment]
in mavenCentral() there is no opencv 10.
i found another maven with opencv 10.
i will added to the list.

**Comment by talregev** [comment]
please add two links also:

http://central.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/
http://central.maven.org/maven2/nu/pattern/opencv/

to README file.

**Comment by stonier** [comment]
Ah..so it seems `org/bytedeco/javacpp-presets/` has a `2.4.10` version in `mavenCentral()`. Let's drop opencv from here then unless there is another reason you'd like to see it here.

**Comment by stonier** [comment]
> Which project from rosjava pull from this repository?

I think you mean where did rosjava_mvn_repo get all these rosjava dependencies like netty? I am not sure - they were already collected when I came along.

> some of the jar version can be update like javadns 2.1.6 instead of 2.1.1
> and there a new project of netty. like netty-all
> maybe the interface in this jar didn't change and can be added easily to rosjava project.

We could upgrade, but that should be tested (not just compiled). If there isn't a good reason to upgrade these dependencies I'd leave them be - if it's working, don't break it.

**Comment by talregev** [comment]
how you add here a quote?

"I think you mean where did rosjava_mvn_repo get all these rosjava dependencies like netty? I am not sure - they were already collected when I came along."

no. I mean which project from rosjava are pulling from this repository.
I know that rosjava core is using javadns v2.1.1 insted the new one 2.1.6, i am not sure, 
but i think it don't pull the jar from this repository. 

" where did rosjava_mvn_repo get all these rosjava dependencies"

I know where to get all these dependencies, i gave you those link and you publish them on
your README file.


when you build Rosjava indigo where you change the link that it pull from the new location? 

"We could upgrade, but that should be tested (not just compiled). If there isn't a good reason to upgrade these dependencies I'd leave them be - if it's working, don't break it."

you are right, it should also tested. most of the jars are update because bug fix and act,
any way my methodology is to use the most new jars as possible.

**Comment by talregev** [comment]
@stonier i think i will delete my maven repository  and reconstruct it from your build.
I will remove all the jars dependency like javadns, netty and etc. 

then you can recompile the rosjava core and tell me it ok.
anyway i will create file that call maven.gradle that include all the maven link we publish,
and put it here, in the repository like the buildscript.gradle i added.
that user can be added the file easly to the project and gradle will be discovered it, if it not already discovery it by using mavenCentral().

i will do it in the night. 

tal.

**Comment by stonier** [comment]
> no. I mean which project from rosjava are pulling from this repository.
> I know that rosjava core is using javadns v2.1.1 insted the new one 2.1.6, i am not sure, 
> but i think it don't pull the jar from this repository.

Ah...it should get them from here, but if not, it will fallback to the springsource repos and then finally maven central. The sequence is listed in the [ros gradle plugin](https://github.com/rosjava/rosjava_bootstrap/blob/indigo/gradle_plugins/src/main/groovy/org/ros/gradle_plugins/RosPlugin.groovy#L21.

**Comment by stonier** [comment]
Rebuilding sounds like a good idea...we probably don't need anything from central.maven.orgl as well (*should* be discoverable to us already).

**Comment by talregev** [comment]
> Ah...it should get them from here, but if not, it will fallback to the springsource repos and then finally maven central. The sequence is listed in the ros gradle plugin.

I think that all ros gradle plugin need to update this file:
https://github.com/talregev/rosjava_mvn_repo/blob/master/maven.gradle

and take the jars from central and not from ours repositories.

**Comment by stonier** [comment]
> i think it can be discovered,

Yes...just tested it. Discovered fine with just a dependency as you listed below. These are standard gradle-maven style dependencies though.

> but need to add to project something like this:
> compile "org.bytedeco.javacpp-presets:opencv:2.4.10-0.10"
> compile "nu.pattern:opencv:2.4.9-7"

**Comment by stonier** [comment]
> I think that all ros gradle plugin need to update this file:
> https://github.com/talregev/rosjava_mvn_repo/blob/master/maven.gradle
> and take the jars from central and not from ours repositories.

Currently it falls back to central. Might be nice to put central first - but lets get this working and synced first and then worry about that as a next step.

**Comment by stonier** [comment]
I just built the [rosjava indigo sources](http://wiki.ros.org/rosjava/Tutorials/indigo/Source%20Installation) with a few bugfixes along the way. Most notable - `gradle 1.11` -> `gradle 2.2.1` everywhere.

**Pull request closed without merging**
