### PR TITLE
Clean the repository:

### PR DESCRIPTION
**Pull request by talregev**
From [issue][1] #19
- commons-pool/commons-pool/1.6
- dnsjava/dnsjava/2.1.1
- io/netty/netty/3.5.2.Final
- junit/junit
- com/google/guava/
- com/google/code/findbugs/jsr305/1.3.9
- org/apache/
- org/sonatype/oss/oss-parent/
- xml-apis/xml-apis/1.0.b2

I almost sure all projects take the jars from original maven repositories.
TODO: need update indexes.

[1]:https://github.com/rosjava/rosjava_mvn_repo/issues/19

### CODE REVIEW

**Comment by talregev** [comment]
@adamantivm can you check?

**Comment by adamantivm** [comment]
Thanks for the help with this.
@talregev just curious, what is your main motivation for this? Specifically, was this causing any particular problems to you?
I like the idea of using the original sources of artifacts but I think @stonier 's original idea was to use this as a cache so as to reduce build breakages due to problems with dependencies. I don't think that is a bad idea.

**Comment by talregev** [comment]
It not casing me any problem. It more correct programming like this. 
This jars already found on the cloud of maven.
It take less space for this repository.
If in the future we want to change the versions of this jars, we don't need to copy each time, and manage this repository. 
And I think, the projects already take first from the cloud, then from this repository.

**Comment by adamantivm** [comment]
@talregev I haven't forgotten about this. I would like to test it and that will take me a bit of time to set-up everything, that's why I'm slow. I also thought that since it is not a blocker to other things, it doesn't have very high priority. But eventually I will get to it. I tend to agree with your view.

**Comment by adamantivm** [comment]
I was finally able to test this. For the record, what I did was to temporarily alter rosjava_bootstrap, specifically the RosPlugin to point to a local copy of the rosjava_mvn_repo and attempt build with that configuration. I can see the artifacts correctly being pulled from other authoritative sources if using your cleaned-up for.
Merge upcoming.

**Comment by talregev** [comment]
Thanks! :+1: 
When I have more time, I will pull request my cv_bridge java library. 
http://wiki.ros.org/cv_bridge/Tutorials/Converting%20between%20ROS%20images%20and%20OpenCV%20images%20(Android%20Java) 
https://github.com/talregev/android_cv_bridge

**Comment by adamantivm** [comment]
sounds great! please do.

**Pull request merged**
