### PR TITLE
Add new tango ros streamer release

### PR DESCRIPTION
**Pull request by PerrineAguiar**
This PR adds artifacts from the new release of TangoRosStreamer

### CODE REVIEW

**Comment by PerrineAguiar** [comment]
@jubeira @adamantivm ptal

**Comment by adamantivm** [comment]
Thank you @PerrineAguiar ! One question: did you intend to add the APK as well? So far we have only published the library (AAR).

**Comment by jubeira** [comment]
Great! The index was updated right? Looks good!

**Comment by PerrineAguiar** [comment]
@adamantivm I added the APK because I saw you added it the first time for version 1.0.13.
@jubeira I've juts run the update_index script. I think it is ok now. 
Is there a way to test that it is working as expected?

**Comment by adamantivm** [comment]
Looks great, thanks @PerrineAguiar !

**Pull request merged**
